
> client@1.0.0 preview
> vite preview --host=0.0.0.0 --port=8080

  ➜  Local:   http://localhost:8080/
  ➜  Network: http://172.31.15.69:8080/
9:51:22 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
9:51:29 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
9:53:53 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
9:54:45 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
9:56:42 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
9:56:47 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
./run_client.sh: line 4:  7112 Hangup                  npm run preview
Client crashed. Restarting...

> client@1.0.0 preview
> vite preview --host=0.0.0.0 --port=8080

  ➜  Local:   http://localhost:8080/
  ➜  Network: http://172.31.15.69:8080/
10:00:48 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
10:15:21 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
10:15:45 PM [vite] http proxy error at /user/checkLogged:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
(node:19414) Warning: An error event has already been emitted on the socket. Please use the destroy method on the socket while handling a 'clientError' event.
(Use `node --trace-warnings ...` to show where the warning was created)
Terminated
Client crashed. Restarting...

> client@1.0.0 preview
> vite preview --host=0.0.0.0 --port=80

  ➜  Local:   http://localhost:80/
  ➜  Network: http://172.31.15.69:80/
